[CmdletBinding()]
param(
    [Parameter(Mandatory = $false)]
    [string]$LibraryRoot = "D:\素材库2",

    [Parameter(Mandatory = $false)]
    [switch]$SkipInstall,

    [Parameter(Mandatory = $false)]
    [switch]$AllowSystemDrive
)

$ErrorActionPreference = "Stop"
$projectRoot = [System.IO.Path]::GetFullPath((Split-Path -Parent $PSScriptRoot))
$libraryPath = [System.IO.Path]::GetFullPath($LibraryRoot)
$systemRoot = [System.IO.Path]::GetPathRoot($env:SystemRoot)
$projectDrive = [System.IO.Path]::GetPathRoot($projectRoot)
$libraryDrive = [System.IO.Path]::GetPathRoot($libraryPath)

if (-not $AllowSystemDrive) {
    if ($projectDrive -ieq $systemRoot) {
        throw "Project is on the system drive ($systemRoot). Move it to another drive, or explicitly use -AllowSystemDrive."
    }
    if ($libraryDrive -ieq $systemRoot) {
        throw "Material library is on the system drive ($systemRoot). Choose another drive with -LibraryRoot."
    }
}

$databasePath = Join-Path $projectRoot "data\library.db"
$cachePath = Join-Path $projectRoot "cache"
$environmentPath = Join-Path $projectRoot ".venv"
$ffmpegPath = Join-Path $environmentPath "Library\bin\ffmpeg.exe"
$ffprobePath = Join-Path $environmentPath "Library\bin\ffprobe.exe"
$envPath = Join-Path $projectRoot ".env"

foreach ($directory in @($libraryPath, (Split-Path -Parent $databasePath), $cachePath)) {
    if (-not (Test-Path -LiteralPath $directory)) {
        New-Item -ItemType Directory -Path $directory | Out-Null
    }
}

$portableValues = [ordered]@{
    FOHE_LIBRARY_ROOT = $libraryPath.Replace("\", "/")
    FOHE_DATABASE_PATH = "./data/library.db"
    FOHE_CACHE_ROOT = "./cache"
    FOHE_FFMPEG_PATH = "./.venv/Library/bin/ffmpeg.exe"
    FOHE_FFPROBE_PATH = "./.venv/Library/bin/ffprobe.exe"
}

$existingNames = @{}
if (Test-Path -LiteralPath $envPath) {
    foreach ($line in [System.IO.File]::ReadAllLines($envPath)) {
        if ($line -match '^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=') {
            $existingNames[$Matches[1]] = $true
        }
    }
} else {
    [System.IO.File]::WriteAllText(
        $envPath,
        "# Local-only configuration. Never commit this file.`r`n",
        [System.Text.UTF8Encoding]::new($false)
    )
}

$missingLines = @()
foreach ($entry in $portableValues.GetEnumerator()) {
    if (-not $existingNames.ContainsKey($entry.Key)) {
        $missingLines += "$($entry.Key)=$($entry.Value)"
    }
}
if ($missingLines.Count -gt 0) {
    $block = "`r`n# Portable paths generated by setup_portable_workstation.ps1`r`n"
    $block += ($missingLines -join "`r`n") + "`r`n"
    [System.IO.File]::AppendAllText(
        $envPath,
        $block,
        [System.Text.UTF8Encoding]::new($false)
    )
}

if (-not $SkipInstall) {
    & (Join-Path $PSScriptRoot "setup_python_env.ps1")
    if ($LASTEXITCODE -ne 0) {
        throw "Python environment setup failed."
    }
}

if (Test-Path -LiteralPath (Join-Path $environmentPath "python.exe")) {
    & (Join-Path $environmentPath "python.exe") (Join-Path $projectRoot "app.py") --check-config
    if ($LASTEXITCODE -ne 0) {
        throw "Runtime configuration check failed."
    }
}

Write-Host "Portable workstation configuration is ready."
Write-Host "Project:  $projectRoot"
Write-Host "Library:  $libraryPath"
Write-Host "Database: $databasePath"
Write-Host "Cache:    $cachePath"
Write-Host "Python:   $(Join-Path $environmentPath 'python.exe')"
Write-Host "FFmpeg:   $ffmpegPath"
Write-Host "FFprobe:  $ffprobePath"
Write-Host "Existing .env values and credentials were not overwritten."
